// <auto-generated />
using EcommerceApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EcommerceApp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EcommerceApp.Entities.DomainModels.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mobile"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Microwave"
                        },
                        new
                        {
                            Id = 3,
                            Name = "TV"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Refrigerator"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Shoes"
                        });
                });

            modelBuilder.Entity("EcommerceApp.Entities.DomainModels.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasPrecision(10, 2)
                        .HasColumnType("decimal(10,2)");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 5,
                            Name = "Nike sneaker",
                            Price = 15000m,
                            Rating = 1.0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 2,
                            Name = "Adidas sports",
                            Price = 2000m,
                            Rating = 2.0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 3,
                            Name = "Samsung 40",
                            Price = 5000m,
                            Rating = 3.5
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 4,
                            Name = "LG",
                            Price = 10000m,
                            Rating = 4.0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 1,
                            Name = "Iphone 14",
                            Price = 100000m,
                            Rating = 5.0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 1,
                            Name = "One Plus",
                            Price = 10000m,
                            Rating = 2.0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 1,
                            Name = "Vivo 10",
                            Price = 10000m,
                            Rating = 3.0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 1,
                            Name = "Samsung Galaxy",
                            Price = 10000m,
                            Rating = 4.0
                        });
                });

            modelBuilder.Entity("EcommerceApp.Entities.DomainModels.Product", b =>
                {
                    b.HasOne("EcommerceApp.Entities.DomainModels.Category", "Category")
                        .WithMany("Products")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EcommerceApp.Entities.DomainModels.Category", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
